# Загружаем исходные данные к сегодняшнему семинару ✈

In [1]:
from google.colab import files
uploaded = files.upload()

Saving dataset_cost.csv to dataset_cost.csv

# Вспомним когортный отчет с последнего семинара ⏰

In [ ]:
т  тimport io
import pandas as pd

df = pd.read_csv(io.BytesIO(uploaded['dataset.csv']))
df_spend = pd.read_csv(io.BytesIO(uploaded['dataset_cost.csv']))
df_ads = pd.read_csv(io.BytesIO(uploaded['dataset_ad.csv']))

display(df)
display(df_spend)
display(df_ads)

,event_date,app_version,country_code,install_date,media_source,campaign_name,appsflyer_id,is_organic,payments,revenue_usd,ad_revenue_usd,sessions,playtime
0,2022-04-09,0.1.75.1,SG,2022-04-09,bytedanceglobal_int,EM_AND_SEA_Purchase_IT2_0604,1649548002569-6720420720726321605,False,0,0.0,0.000000,1,4
1,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649545238733-4551347935758619924,False,0,0.0,0.000000,1,2
2,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649540322226-5366969563919899948,False,0,0.0,0.000000,1,2
3,2022-04-09,0.1.75.1,UK,2022-04-07,bytedanceglobal_int,EM_AND_T1_Purchase_IT2_0604,1649337475698-617904100123526593,False,0,0.0,0.000000,1,1
4,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649544985557-9160306254813664580,False,0,0.0,0.000000,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
690370,2022-07-31,NaN,PH,2022-07-28,organic,organic,1659003289354-9130797695840500796,True,0,0.0,0.002614,1,1
690371,2022-07-31,NaN,AE,2022-07-28,organic,organic,1659020308480-7169513513931602186,True,0,0.0,0.012164,1,1
690372,2022-07-31,NaN,DZ,2022-07-29,organic,organic,1659059933950-196412188438371439,True,0,0.0,0.000195,1,1
690373,2022-07-31,NaN,FR,2022-07-29,organic,organic,1659086493021-6361713490086303799,True,0,0.0,0.021129,1,1
690374,2022-07-31,NaN,PH,2022-07-30,organic,organic,1659163795895-4158823392120234659,True,0,0.0,0.005909,1,1

                            appsflyer_id install_date  user_cost
0      1652759784623-2460704185261443885   2022-05-17   0.642349
1      1655526699783-8574419046565448176   2022-06-18   0.157631
2      1654492019018-1278649829463899192   2022-06-06   0.997820
3      1653160250232-1033278339103232135   2022-05-21   0.872417
4      1649518196275-5026948722442160790   2022-04-09   0.898276
...                                  ...          ...        ...
22203  1649024273848-7424286570492263703   2022-04-03   0.982764
22204  1650162758375-5050707578358937950   2022-04-17   0.686304
22205  1651369491964-2638329077315167130   2022-05-01   0.774207
22206  1647973558010-3666611778683093039   2022-03-22   0.807016
22207  1653692431243-1040103588190937930   2022-05-27   0.137207

[22208 rows x 3 columns]

,event_date,country_code,revenue_usd,impressions,ad_network,network_placement
0,2022-03-02,IR,0.000872,2,MINTEGRAL_BIDDING,1766942
1,2022-03-02,ZA,0.006000,3,IRONSOURCE_NETWORK,7170927
2,2022-03-02,IE,0.019875,2,MINTEGRAL_BIDDING,1766942
3,2022-03-02,US,0.016000,2,IRONSOURCE_NETWORK,7170931
4,2022-03-03,MM,0.007060,11,APPLOVIN_NETWORK,REWARD
...,...,...,...,...,...,...
47778,2022-03-02,VN,0.001000,1,UNITY_NETWORK,TT_REW_1
47779,2022-03-02,MD,0.010501,8,APPLOVIN_NETWORK,REWARD
47780,2022-03-02,CH,0.015000,1,UNITY_NETWORK,TT_REW_15
47781,2022-03-02,MY,0.004000,2,IRONSOURCE_NETWORK,7170927
47782,2022-03-02,RO,0.010000,1,UNITY_NETWORK,TT_REW_10

In [ ]:
df['event_date'] = pd.to_datetime(df['event_date'])
df['install_date'] = pd.to_datetime(df['install_date'])

df_usa_spend = pd.merge(df[(df['install_date'] >= '2022-04-01') & (df['country_code'] == 'US')], df_spend, on='appsflyer_id')

df_cohort_spend = df_usa_spend.groupby('install_date_x', as_index = False).agg({'user_cost':'sum', 'appsflyer_id':'nunique', 'revenue_usd':'sum', 'ad_revenue_usd':'sum'}).rename(columns = {'install_date_x':'install_date', 'user_cost':'spend_daily', 'appsflyer_id':'installs'})

df_cohort_spend['cpi'] = df_cohort_spend['spend_daily'] / df_cohort_spend['installs']
df_cohort_spend['total_revenue'] = df_cohort_spend['revenue_usd'] + df_cohort_spend['ad_revenue_usd']

df_cohort_spend = df_cohort_spend.fillna(0)

df_cohort_spend['rpi'] = df_cohort_spend['total_revenue'] / df_cohort_spend['installs']
df_cohort_spend['profit'] = df_cohort_spend['total_revenue'] - df_cohort_spend['spend_daily']
df_cohort_spend['roi'] = df_cohort_spend['total_revenue']*100 / df_cohort_spend['spend_daily']

df_cohort_spend

,install_date,spend_daily,installs,revenue_usd,ad_revenue_usd,cpi,total_revenue,rpi,profit,roi
0,2022-04-01,63.591341,92,36.92,8.303722,0.691210,45.223722,0.491562,-18.367619,71.116164
1,2022-04-02,91.133512,98,73.84,10.135525,0.929934,83.975525,0.856893,-7.157987,92.145604
2,2022-04-03,78.878499,96,39.90,8.529624,0.821651,48.429624,0.504475,-30.448875,61.397751
3,2022-04-04,32.720373,31,9.99,6.371984,1.055496,16.361984,0.527806,-16.358389,50.005494
4,2022-04-05,4.475612,7,0.00,0.464736,0.639373,0.464736,0.066391,-4.010876,10.383742
...,...,...,...,...,...,...,...,...,...,...
97,2022-07-07,8.449847,11,48.89,0.118729,0.768168,49.008729,4.455339,40.558882,579.995445
98,2022-07-08,3.222925,6,0.00,0.000000,0.537154,0.000000,0.000000,-3.222925,0.000000
99,2022-07-09,2.442983,2,0.00,0.523343,1.221492,0.523343,0.261672,-1.919640,21.422293
100,2022-07-10,0.518195,1,0.00,0.000000,0.518195,0.000000,0.000000,-0.518195,0.000000
101,2022-07-11,0.728461,2,0.00,0.000000,0.364231,0.000000,0.000000,-0.728461,0.000000

Вспомним, что такое LTV и какие есть методы расчета этой метрики ✌

Можно считать, что **накопительный ARPU (cARPU) будет равен LTV** некоторой когорты.
Добавим LTV в наш когортный отчет. И посчитаем LTV помесячно для США.

In [ ]:
df_ltv = df_cohort_spend.copy()
df_ltv['install_month'] = df_ltv['install_date'].dt.month

df_ltv = df_ltv.groupby('install_month', as_index = False).agg({'installs':'sum', 'spend_daily':'sum', 'total_revenue':'sum'}).rename(columns = {'spend_daily':'spend_month'})

df_ltv

   install_month  installs  spend_month  total_revenue
0              4      3153  3000.565276    1658.087717
1              5      4798  3776.281935    1346.994905
2              6      7140  5842.848466    1028.271722
3              7      1081   829.598473      84.265624

Добавляем LTV и CPI. Рассчитаем помесячную маржинальность через ROI

In [ ]:
df_ltv['ltv'] = df_ltv['total_revenue'] / df_ltv['installs']

df_ltv['cpi'] = df_ltv['spend_month'] / df_ltv['installs']

df_ltv['roi'] = df_ltv['total_revenue']*100 / df_ltv['spend_month']

df_ltv

,install_month,installs,spend_month,total_revenue,ltv,cpi,roi
0,4,3153,3000.565276,1658.087717,0.525876,0.951654,55.259178
1,5,4798,3776.281935,1346.994905,0.280741,0.787053,35.669871
2,6,7140,5842.848466,1028.271722,0.144016,0.818326,17.598809
3,7,1081,829.598473,84.265624,0.077952,0.767436,10.157399

Какие выводы можем сделать по LTV для США? 🔎 Какая метрика уже предствленная в когортном отчете максимально близка к LTV?

# Прогнозирование LTV. Коэффициентная модель 📈

Попробуем рассчитать коэффициентную модель LTV для недельных когорт. При этом рассматривать будем прогноз LTV 14го дня на основе LTV 3го дня жизни когорты.

In [ ]:
df_forecast = df[(df['country_code'] == 'US') & (df['install_date'] >= '2022-04-01')].copy()

df_forecast['activity_day'] = (df_forecast['event_date'] - df_forecast['install_date']).dt.days
df_forecast['start_of_week'] = df_forecast['install_date'] - pd.to_timedelta(df_forecast['install_date'].dt.dayofweek, unit='d')

df_forecast

,event_date,app_version,country_code,install_date,media_source,campaign_name,appsflyer_id,is_organic,payments,revenue_usd,ad_revenue_usd,sessions,playtime,activity_day,start_of_week
1,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649545238733-4551347935758619924,False,0,0.0,0.000000,1,2,0,2022-04-04
2,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649540322226-5366969563919899948,False,0,0.0,0.000000,1,2,0,2022-04-04
4,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649544985557-9160306254813664580,False,0,0.0,0.000000,1,2,0,2022-04-04
5,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649543024686-2013762249241156998,False,0,0.0,0.000000,1,1,0,2022-04-04
6,2022-04-09,0.1.75.1,US,2022-04-09,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1649533663096-5517179448405042344,False,0,0.0,0.000000,1,14,0,2022-04-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690334,2022-07-31,NaN,US,2022-07-26,organic,organic,1658841281188-256968299414403125,True,0,0.0,0.008423,1,1,5,2022-07-25
690341,2022-07-31,NaN,US,2022-05-03,bytedanceglobal_int,EM_AND_US_Purchase_IT1_2703,1651621598582-5813668387280636203,False,0,0.0,0.040360,1,1,89,2022-05-02
690343,2022-07-31,NaN,US,2022-05-27,organic,organic,1653616964386-4004317216029101104,True,0,0.0,0.107781,1,1,65,2022-05-23
690355,2022-07-31,NaN,US,2022-07-05,organic,organic,1657041977147-1950292838227389049,True,0,0.0,0.027322,1,1,26,2022-07-04
690363,2022-07-31,NaN,US,2022-07-20,organic,organic,1658298946847-1228283020255368063,True,0,0.0,0.005983,1,1,11,2022-07-18

Посчитаем для недельных когорт значение LTV на 3ий день жизни когорты.

In [ ]:
df_ltv_day3 = df_forecast[df_forecast['activity_day'] <= 3].groupby('start_of_week', as_index = False).agg({'appsflyer_id':'nunique', 'revenue_usd':'sum', 'ad_revenue_usd':'sum'}).rename(columns = {'appsflyer_id':'installs'})
df_ltv_day3['total_revenue'] = df_ltv_day3['revenue_usd'] + df_ltv_day3['ad_revenue_usd']
df_ltv_day3['ltv_day3'] = df_ltv_day3['total_revenue'] / df_ltv_day3['installs']

df_ltv_day3

,start_of_week,installs,revenue_usd,ad_revenue_usd,total_revenue,ltv_day3
0,2022-03-28,433,133.690000,32.672688,166.362688,0.384209
1,2022-04-04,1061,365.110000,62.427427,427.537427,0.402957
2,2022-04-11,1613,541.850000,119.282737,661.132737,0.409878
3,2022-04-18,1564,582.720000,105.906085,688.626085,0.440298
4,2022-04-25,1696,765.550000,116.929261,882.479261,0.520330
5,2022-05-02,1960,908.090000,163.414856,1071.504856,0.546686
6,2022-05-09,2055,1155.800000,164.733061,1320.533061,0.642595
7,2022-05-16,3772,940.830000,173.713825,1114.543825,0.295478
8,2022-05-23,4034,969.360668,149.192435,1118.553103,0.277281
9,2022-05-30,3048,1160.190858,168.033962,1328.224820,0.435769
10,2022-06-06,3670,681.059753,134.764931,815.824684,0.222296
11,2022-06-13,4403,1056.640000,131.817467,1188.457467,0.269920
12,2022-06-20,5462,1156.300000,163.479761,1319.779761,0.241629
13,2022-06-27,5501,1081.650000,166.580193,1248.230193,0.226910
14,2022-07-04,3523,1054.825800,150.694324,1205.520124,0.342186
15,2022-07-11,1985,640.640000,69.467134,710.107134,0.357737
16,2022-07-18,1980,399.100000,62.403470,461.503470,0.233083
17,2022-07-25,1967,545.000655,62.852781,607.853436,0.309026

Посчитаем для недельных когорт значение LTV на 14ый день активности.

In [ ]:
df_ltv_day14 = df_forecast[df_forecast['activity_day'] <= 14].groupby('start_of_week', as_index = False).agg({'appsflyer_id':'nunique', 'revenue_usd':'sum', 'ad_revenue_usd':'sum'}).rename(columns = {'appsflyer_id':'installs'})
df_ltv_day14['total_revenue'] = df_ltv_day14['revenue_usd'] + df_ltv_day14['ad_revenue_usd']
df_ltv_day14['ltv_day14'] = df_ltv_day14['total_revenue'] / df_ltv_day14['installs']

df_ltv_day14

,start_of_week,installs,revenue_usd,ad_revenue_usd,total_revenue,ltv_day14
0,2022-03-28,436,158.640000,39.900953,198.540953,0.455369
1,2022-04-04,1065,428.990000,100.727879,529.717879,0.497388
2,2022-04-11,1620,638.640000,190.183743,828.823743,0.511620
3,2022-04-18,1572,656.460000,161.889451,818.349451,0.520579
4,2022-04-25,1701,842.340000,171.450351,1013.790351,0.595997
5,2022-05-02,1967,1043.680000,242.451383,1286.131383,0.653854
6,2022-05-09,2071,1236.500000,244.217588,1480.717588,0.714977
7,2022-05-16,3791,1111.370000,263.607811,1374.977811,0.362695
8,2022-05-23,4050,1129.980668,232.331321,1362.311989,0.336373
9,2022-05-30,3061,1311.780858,231.657148,1543.438006,0.504227
10,2022-06-06,3695,827.729753,192.182726,1019.912479,0.276025
11,2022-06-13,4438,1207.220000,195.712718,1402.932718,0.316118
12,2022-06-20,5545,1402.800000,248.820265,1651.620265,0.297858
13,2022-06-27,5538,1356.000000,251.211561,1607.211561,0.290215
14,2022-07-04,3543,1298.865800,224.065101,1522.930901,0.429842
15,2022-07-11,2003,752.390000,106.359678,858.749678,0.428732
16,2022-07-18,1993,472.910000,86.604002,559.514002,0.280740
17,2022-07-25,1970,576.960655,67.467210,644.427865,0.327121

Соединим данные между собой и посчитаем коэффициент LTV 14го дня жизни когорты к 3му дню активности.

In [ ]:
df_forecast_ltv = pd.merge(df_ltv_day3[['start_of_week', 'installs', 'ltv_day3']], df_ltv_day14[['start_of_week', 'ltv_day14']], how='left', on='start_of_week')
df_forecast_ltv['ltv_coef'] = df_forecast_ltv['ltv_day14'] / df_forecast_ltv['ltv_day3']

df_forecast_ltv

   start_of_week  installs  ltv_day3  ltv_day14  ltv_coef
0     2022-03-28       433  0.384209   0.455369  1.185211
1     2022-04-04      1061  0.402957   0.497388  1.234344
2     2022-04-11      1613  0.409878   0.511620  1.248225
3     2022-04-18      1564  0.440298   0.520579  1.182332
4     2022-04-25      1696  0.520330   0.595997  1.145421
5     2022-05-02      1960  0.546686   0.653854  1.196032
6     2022-05-09      2055  0.642595   0.714977  1.112640
7     2022-05-16      3772  0.295478   0.362695  1.227486
8     2022-05-23      4034  0.277281   0.336373  1.213112
9     2022-05-30      3048  0.435769   0.504227  1.157096
10    2022-06-06      3670  0.222296   0.276025  1.241703
11    2022-06-13      4403  0.269920   0.316118  1.171156
12    2022-06-20      5462  0.241629   0.297858  1.232704
13    2022-06-27      5501  0.226910   0.290215  1.278990
14    2022-07-04      3523  0.342186   0.429842  1.256167
15    2022-07-11      1985  0.357737   0.428732  1.198456
16    2022-07-18      1980  0.233083   0.280740  1.204464
17    2022-07-25      1967  0.309026   0.327121  1.058555

Возьмем медиану по LTV коэффициенту, значение которой будем далее использовать для прогноза. Почему в данном случае следует брать медиану а не среднее?

In [ ]:
ltv_coefficient = df_forecast_ltv['ltv_coef'].median()
ltv_coefficient

1.2014603251744864

Используем полученный коэффициент для получения прогнозного значения LTV 14го дня жизни когорты по 3му дню активности.

In [ ]:
df_forecast_ltv = df_forecast_ltv.rename(columns = {'ltv_day14':'ltv_day14_fact'})
df_forecast_ltv['ltv_day14_forecast'] = df_forecast_ltv['ltv_day3'] * ltv_coefficient

df_forecast_ltv

,start_of_week,installs,ltv_day3,ltv_day14_fact,ltv_coef,ltv_day14_forecast
0,2022-03-28,433,0.384209,0.455369,1.185211,0.461612
1,2022-04-04,1061,0.402957,0.497388,1.234344,0.484137
2,2022-04-11,1613,0.409878,0.511620,1.248225,0.492452
3,2022-04-18,1564,0.440298,0.520579,1.182332,0.529001
4,2022-04-25,1696,0.520330,0.595997,1.145421,0.625156
5,2022-05-02,1960,0.546686,0.653854,1.196032,0.656822
6,2022-05-09,2055,0.642595,0.714977,1.112640,0.772053
7,2022-05-16,3772,0.295478,0.362695,1.227486,0.355005
8,2022-05-23,4034,0.277281,0.336373,1.213112,0.333143
9,2022-05-30,3048,0.435769,0.504227,1.157096,0.523560
10,2022-06-06,3670,0.222296,0.276025,1.241703,0.267079
11,2022-06-13,4403,0.269920,0.316118,1.171156,0.324298
12,2022-06-20,5462,0.241629,0.297858,1.232704,0.290308
13,2022-06-27,5501,0.226910,0.290215,1.278990,0.272623
14,2022-07-04,3523,0.342186,0.429842,1.256167,0.411123
15,2022-07-11,1985,0.357737,0.428732,1.198456,0.429806
16,2022-07-18,1980,0.233083,0.280740,1.204464,0.280039
17,2022-07-25,1967,0.309026,0.327121,1.058555,0.371282

Посмотрим полученные результаты на графике.

In [ ]:
import plotly.express as px

fig = px.bar(df_forecast_ltv, x = 'start_of_week', y = ['ltv_day14_fact', 'ltv_day14_forecast'], barmode = 'group')
fig.show()

Прокомментируйте полученные результаты.

# Домашнее задание ✍

Добавьте к своему когортному отчету прогнозирование LTV (можно воспользоваться также коэффициентами LTV 14го дня жизни когорты по отношению к LTV 3го дня жизни).

In [ ]:
ex3=pd.read_sql(f'''
with all_data as
(with data as

         (SELECT  event_time, user_id, platform,
            min(event_time) filter (where event_name='FirstLaunchApp') OVER(PARTITION BY user_id) as date_install,
            case WHEN country in ('RU', 'AZ', 'AM', 'BY','KZ', 'KG','MD', 'TJ', 'UZ', 'UA', 'TM') then 'CIS'
                 WHEN country in ('CA', 'US') then 'NA' else 'Other' end as region,
            user_type,revenue_usd

            FROM data_viz_1068.project_dataset
            WHERE user_id in
                    (SELECT user_id
                    FROM data_viz_1068.project_dataset
                    WHERE event_name='FirstLaunchApp')),

    temp_df as(
        SELECT case when user_id>0 then '1' end as  merge,(ROW_NUMBER() OVER())-1 num
        FROM data_viz_1068.project_dataset
        WHERE event_name='FirstLaunchApp'
        LIMIT 91
    )

        SELECT lifetime, cast(users as float)/cast(max as float) as ret_roll, platform, region,user_type,c_dau,
        sum(rev) OVER(PARTITION BY platform, region,user_type ORDER BY  lifetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS с_rev_usd
        FROM
            (SELECT num as lifetime, count(distinct user_id) as users,platform, region,user_type,
            max(count(distinct user_id)) over (partition by platform, region,user_type) as max, sum(rev) as rev,
            sum(count(distinct user_id)) OVER(PARTITION BY platform, region,user_type ORDER BY  num ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS c_dau

            FROM
            (SELECT lifetime,num, user_id,platform, region,user_type,rev
            FROM
                    (SELECT *
                    FROM (SELECT max(extract(day from date_trunc('days',event_time-date_install))) as lifetime,
                    user_id, platform, region,user_type, case when user_id>0 then '1' end as  merge,sum(revenue_usd) as rev
                    FROM data
                    WHERE event_time <=(date_install+INTERVAL '3' MONTH) and region !='Other'
                    GROUP BY 2,3,4,5
                    ORDER BY 1) as l

                    JOIN temp_df  as i
                    ON l.merge=i.merge) as o
            WHERE lifetime>=num
            ) as f
            GROUP BY 1,3,4,5) as w)

SELECT lifetime,platform, region,user_type,arpdau*sum_roll as ltv
FROM
    (SELECT lifetime, platform, region,user_type, (с_rev_usd/c_dau) as arpdau,
    sum(ret_roll) OVER(PARTITION BY platform, region,user_type ORDER BY  lifetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS sum_roll
    FROM all_data) as e


''', con=engine)